### ISSUE TITLE
Updating psr/log Composer Requirement for Compatibility with Drupal 10

### ISSUE THREAD

**Issue by attheshow** [lordelph/php-sip2#5]
We're using this library on a Drupal 9 site and are actively working on updating to Drupal 10 (D9 is end-of-life in November). When running composer updates today, I noticed the following error in relation to the psr/log dependency:

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires drupal/core 10.0.9 -> satisfiable by drupal/core[10.0.9].
    - drupal/intercept dev-1.x requires lordelph/php-sip2 ^2.0 -> satisfiable by lordelph/php-sip2[2.1.0, 2.1.1, v2.x-dev].
    - lordelph/php-sip2[2.1.0, ..., v2.x-dev] require psr/log ^1.0 -> satisfiable by psr/log[1.0.0, ..., 1.1.4].
    - You can only install one version of a package, so only one of these can be installed: psr/log[1.0.0, ..., 1.1.4, 2.0.0, 3.0.0, 3.x-dev].
    - drupal/intercept 1.x-dev is an alias of drupal/intercept dev-1.x and thus requires it to be installed too.
    - drupal/core 10.0.9 requires psr/log ^3.0 -> satisfiable by psr/log[3.0.0, 3.x-dev].
    - Root composer.json requires drupal/intercept 1.x-dev -> satisfiable by drupal/intercept[1.x-dev (alias of dev-1.x)].`

**Comment by attheshow** [comment]
[php-sip2-psr-v3.patch](https://github.com/lordelph/php-sip2/files/11735802/php-sip2-psr-v3.patch)

**Comment by lordelph** [comment]
Thanks for the patch - will review asap and will assign a new version number as appropriate.

**Comment by lordelph** [comment]
OK - released as a new major version 3.0.0 - let me know if that works for you.

**Comment by attheshow** [comment]
That worked. Thanks so much! 😊
